#!/usr/bin/env python3
"""
onchain_zktest.py — End-to-End ZK Proof → Algorand Testnet Test
=================================================================
Flow:
  1. Read proof.json + public.json (already generated by snarkjs)
  2. Verify proof off-chain with verification_key.json (issuer backend step)
  3. If valid → extract nullifier from public signals
  4. Register nullifier on NullifierRegistry (app_id=756272073) on Testnet
  5. Verify on-chain state changed (total_registered incremented)

This simulates the exact V1 flow:
  Browser proves locally → sends proof+signals to issuer backend
  Backend verifies → calls NullifierRegistry.register()
"""
import base64
import hashlib
import json
import logging
import os
import subprocess
import sys
from pathlib import Path

from dotenv import load_dotenv
from algosdk import account, mnemonic, transaction
from algosdk.v2client import algod

load_dotenv(Path(__file__).parent.parent.parent.parent / "zk-kyc/projects/zk-kyc/.env")

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)-8s: %(message)s")
logger = logging.getLogger(__name__)

# Paths
CIRCOM_DIR      = Path(__file__).parent
PROOF_JSON      = CIRCOM_DIR / "build/proof.json"
PUBLIC_JSON     = CIRCOM_DIR / "build/public.json"
VK_JSON         = CIRCOM_DIR / "build/verification_key.json"
SNARKJS         = CIRCOM_DIR / "node_modules/snarkjs/cli.js"
DEPLOYED_JSON   = Path(__file__).parent.parent.parent.parent / "zk-kyc/projects/zk-kyc/deployed_contracts.json"

ALGOD_SERVER    = "https://testnet-api.algonode.cloud"


def sel(sig: str) -> bytes:
    """ABI method selector."""
    return hashlib.new("sha512_256", sig.encode()).digest()[:4]


def get_algod():
    token = os.environ.get("ALGOD_TOKEN", "")
    return algod.AlgodClient(token, ALGOD_SERVER)


def get_pk():
    return mnemonic.to_private_key(os.environ["DEPLOYER_MNEMONIC"])


def wait_confirmed(client, txid, timeout=12):
    last_round = client.status()["last-round"]
    for _ in range(timeout):
        info = client.pending_transaction_info(txid)
        if info.get("confirmed-round", 0) > 0:
            return info
        client.status_after_block(last_round + 1)
        last_round += 1
    raise TimeoutError(f"Not confirmed: {txid}")


def read_global_state(client, app_id: int) -> dict:
    info = client.application_info(app_id)
    state = {}
    for kv in info.get("params", {}).get("global-state", []):
        key = base64.b64decode(kv["key"]).decode("utf-8", errors="replace")
        val = kv["value"]
        state[key] = base64.b64decode(val["bytes"]) if val["type"] == 1 else val["uint"]
    return state


# ── Step 1: Verify proof off-chain (issuer backend role) ──────────────────────
def verify_proof_offchain():
    logger.info("=== Step 1: Off-chain ZK Proof Verification ===")

    result = subprocess.run(
        ["node", str(SNARKJS), "groth16", "verify",
         str(VK_JSON), str(PUBLIC_JSON), str(PROOF_JSON)],
        capture_output=True, text=True, cwd=str(CIRCOM_DIR)
    )
    output = result.stdout + result.stderr
    logger.info(f"snarkjs output: {output.strip()}")

    if result.returncode != 0 or "OK!" not in output:
        raise RuntimeError(f"Proof verification FAILED!\n{output}")

    logger.info("  Proof verified OFF-CHAIN ✅")


# ── Step 2: Extract public signals ────────────────────────────────────────────
def extract_public_signals():
    logger.info("\n=== Step 2: Extract Public Signals ===")

    public = json.loads(PUBLIC_JSON.read_text())
    # public.json order matches circuit signal order:
    # [nullifier, merkleRoot, appId, isIndian, isAdult, isKYCVerified, ...mimcConstants...]
    nullifier_int   = int(public[0])
    merle_root_int  = int(public[1])
    app_id_public   = int(public[2])
    is_indian       = int(public[3])
    is_adult        = int(public[4])
    is_kyc_verified = int(public[5])

    # Convert nullifier to 32-byte big-endian
    nullifier_bytes = nullifier_int.to_bytes(32, "big")

    logger.info(f"  nullifier     = {nullifier_int}")
    logger.info(f"  merkleRoot    = {merle_root_int}")
    logger.info(f"  appId         = {app_id_public}")
    logger.info(f"  isIndian      = {is_indian}")
    logger.info(f"  isAdult       = {is_adult}")
    logger.info(f"  isKYCVerified = {is_kyc_verified}")
    logger.info(f"  nullifier_hex = {nullifier_bytes.hex()}")

    # Sanity checks (issuer backend would do these)
    assert is_indian       == 1, "Must be Indian"
    assert is_adult        == 1, "Must be adult (>=18)"
    assert is_kyc_verified == 1, "Must be KYC verified"

    return nullifier_bytes, nullifier_int


# ── Step 3: Register nullifier on-chain ───────────────────────────────────────
def register_nullifier_onchain(nullifier_bytes: bytes):
    logger.info("\n=== Step 3: On-Chain Registration ===")

    deployed = json.loads(DEPLOYED_JSON.read_text())
    nr_id    = deployed["nullifier_registry"]["app_id"]
    nr_addr  = deployed["nullifier_registry"]["app_address"]

    client = get_algod()
    pk     = get_pk()
    sender = account.address_from_private_key(pk)

    logger.info(f"  NullifierRegistry app_id = {nr_id}")
    logger.info(f"  Deployer                 = {sender}")

    state_before = read_global_state(client, nr_id)
    total_before = state_before.get("total_registered", 0)
    logger.info(f"  total_registered before  = {total_before}")

    # ABI encode nullifier as arc4.DynamicArray<UInt8>
    # Format: 2-byte big-endian length prefix + bytes
    enc_nullifier = len(nullifier_bytes).to_bytes(2, "big") + nullifier_bytes

    # ABI encode wallet address (32 bytes raw)
    wallet_bytes = bytes.fromhex(
        "".join(f"{x:02x}" for x in transaction.encoding.decode_address(sender))
    )

    # Check ABI method selector for register(byte[],address)void
    register_sel = sel("register(byte[],address)void")
    logger.info(f"  register() selector = {register_sel.hex()}")

    # Fund NullifierRegistry for box MBR (key_prefix "nul_" + 32 bytes)
    # Box MBR = 2500 + 400*(len(box_name) + len(box_value))
    # box_name = "nul_" + 32 bytes = 36 bytes
    # box_value = 32 bytes (wallet address) + extra metadata
    # ≈ 2500 + 400*(36+32) = 2500 + 27200 = 29,700 microALGO ≈ 0.03 ALGO
    sp = client.suggested_params()
    fund_txn = transaction.PaymentTxn(
        sender=sender, sp=sp, receiver=nr_addr, amt=50_000  # 0.05 ALGO for box MBR
    )
    fund_txid = client.send_transaction(fund_txn.sign(pk))
    wait_confirmed(client, fund_txid)
    logger.info(f"  Funded NullifierRegistry 0.05 ALGO (box MBR): {fund_txid}")

    # Call register(nullifier, wallet)
    sp = client.suggested_params()
    box_name = b"nul_" + nullifier_bytes
    reg_txn = transaction.ApplicationNoOpTxn(
        sender=sender, sp=sp, index=nr_id,
        app_args=[register_sel, enc_nullifier, wallet_bytes],
        accounts=[sender],
        boxes=[(nr_id, box_name)],
    )
    reg_txid = client.send_transaction(reg_txn.sign(pk))
    reg_res  = wait_confirmed(client, reg_txid)
    logger.info(f"  register() txn confirmed: {reg_txid}")

    # Verify state changed
    state_after = read_global_state(client, nr_id)
    total_after = state_after.get("total_registered", 0)
    logger.info(f"  total_registered after   = {total_after}")

    assert total_after == total_before + 1, f"Expected {total_before+1}, got {total_after}"
    logger.info("  total_registered incremented ✅")

    return reg_txid, nr_id


# ── Step 4: Verify registration on-chain ─────────────────────────────────────
def verify_registration(nullifier_bytes: bytes, nr_id: int, reg_txid: str):
    logger.info("\n=== Step 4: Verify Registration On-Chain ===")
    client = get_algod()
    pk     = get_pk()
    sender = account.address_from_private_key(pk)
    sp     = client.suggested_params()

    enc_nullifier = len(nullifier_bytes).to_bytes(2, "big") + nullifier_bytes
    box_name      = b"nul_" + nullifier_bytes

    # Call is_registered(nullifier) via dry-run
    is_reg_sel = sel("is_registered(byte[])bool")
    check_txn = transaction.ApplicationNoOpTxn(
        sender=sender, sp=sp, index=nr_id,
        app_args=[is_reg_sel, enc_nullifier],
        boxes=[(nr_id, box_name)],
    )
    dry = client.dryrun(transaction.create_dryrun(client, [check_txn.sign(pk)]))
    txn_res = dry.get("txns", [{}])[0]
    logs    = txn_res.get("logs", [])
    is_reg  = False
    if logs:
        raw    = base64.b64decode(logs[0])
        is_reg = (raw[-1] == 1) if raw else False

    logger.info(f"  is_registered() = {is_reg}")

    print("\n" + "=" * 65)
    print("  END-TO-END ON-CHAIN ZK TEST RESULTS")
    print("=" * 65)
    print(f"  ZK Proof verified off-chain  : OK (snarkjs Groth16)")
    print(f"  Nullifier registered on-chain: {reg_txid}")
    print(f"  Explorer: https://allo.info/tx/{reg_txid}")
    print(f"  is_registered() dry-run      : {is_reg}")
    print(f"  NullifierRegistry app_id     : {nr_id}")
    print("=" * 65)
    print("\n  AlgoKYC ZK proof == on-chain registration WORKS!")
    print("  Private data never left the browser.")
    print("  Only the proof + public signals went to the issuer.")
    print("  The nullifier is now registered immutably on Algorand Testnet.")
    print("=" * 65)


# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    # Check files exist
    for f in [PROOF_JSON, PUBLIC_JSON, VK_JSON]:
        if not f.exists():
            logger.error(f"Missing: {f}")
            logger.error("Run: cd projects/circuits/circom && node scripts/debug_mimc.mjs && node build/kyc_js/generate_witness.js ... && node node_modules/snarkjs/cli.js groth16 prove ...")
            sys.exit(1)

    logger.info("=== AlgoKYC: End-to-End On-Chain ZK Test ===")
    logger.info(f"Proof:   {PROOF_JSON}")
    logger.info(f"Public:  {PUBLIC_JSON}")
    logger.info(f"Network: {ALGOD_SERVER}")

    verify_proof_offchain()
    nullifier_bytes, nullifier_int = extract_public_signals()
    reg_txid, nr_id = register_nullifier_onchain(nullifier_bytes)
    verify_registration(nullifier_bytes, nr_id, reg_txid)


if __name__ == "__main__":
    main()
