// dump_constants.go — dump gnark-crypto MiMC BN254 constants for JS/Circom use
//
// Run: go run . dump-constants
// Output: output/mimc_constants.json + output/mimc_constants.js

package main

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"

	mimcNative "github.com/consensys/gnark-crypto/ecc/bn254/fr/mimc"
)

func runDumpConstants() {
	fmt.Println("=== Dumping gnark-crypto BN254 MiMC constants ===")
	os.MkdirAll("output", 0755)

	constants := mimcNative.GetConstants()
	strs := make([]string, len(constants))
	for i, c := range constants {
		strs[i] = c.String()
	}

	// JSON for general use
	data, _ := json.MarshalIndent(map[string]interface{}{
		"curve":  "BN254",
		"rounds": len(constants),
		"seed":   "seed",
		"values": strs,
		"note":   "Generated by gnark-crypto GetConstants(). Derived via LegacyKeccak256 chain.",
	}, "", "  ")
	os.WriteFile("output/mimc_constants.json", data, 0644)

	// JS module for direct import
	var sb strings.Builder
	sb.WriteString("// gnark-crypto BN254 MiMC constants — auto-generated, do NOT edit\n")
	sb.WriteString("// Source: github.com/consensys/gnark-crypto/ecc/bn254/fr/mimc GetConstants()\n")
	sb.WriteString(fmt.Sprintf("// Curve: BN254, Rounds: %d, Seed: 'seed'\n\n", len(constants)))
	sb.WriteString("export const MIMC_CONSTANTS = [\n")
	for i, s := range strs {
		if i < len(strs)-1 {
			sb.WriteString(fmt.Sprintf("  %sn,\n", s))
		} else {
			sb.WriteString(fmt.Sprintf("  %sn\n", s))
		}
	}
	sb.WriteString("];\n\n")
	sb.WriteString(fmt.Sprintf("export const MIMC_ROUNDS = %d;\n", len(constants)))
	sb.WriteString("export const P = BigInt('21888242871839275222246405745257275088548364400416034343698204186575808495617');\n")
	os.WriteFile("output/mimc_constants.js", []byte(sb.String()), 0644)

	fmt.Printf("✅ %d constants written to output/mimc_constants.json\n", len(constants))
	fmt.Println("✅ JS module written to output/mimc_constants.js")
}
